// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ER0pknUzZqWWZRsdkhFdYWtwHXKb6n8',
    appId: '1:890593335603:web:ede6d905b90ab63b238646',
    messagingSenderId: '890593335603',
    projectId: 'gasplit-e0299',
    authDomain: 'gasplit-e0299.firebaseapp.com',
    storageBucket: 'gasplit-e0299.firebasestorage.app',
    measurementId: 'G-BT82N8XTXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rqSt6Z9VF9s84y5gB73rjMEXbhhd06o',
    appId: '1:890593335603:android:0b54b853869be42e238646',
    messagingSenderId: '890593335603',
    projectId: 'gasplit-e0299',
    storageBucket: 'gasplit-e0299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHXS7w_IW2BPl5P5BrtE8mVV9UJNJaSZk',
    appId: '1:890593335603:ios:dbb4806c07b5d066238646',
    messagingSenderId: '890593335603',
    projectId: 'gasplit-e0299',
    storageBucket: 'gasplit-e0299.firebasestorage.app',
    iosBundleId: 'com.example.gasplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHXS7w_IW2BPl5P5BrtE8mVV9UJNJaSZk',
    appId: '1:890593335603:ios:dbb4806c07b5d066238646',
    messagingSenderId: '890593335603',
    projectId: 'gasplit-e0299',
    storageBucket: 'gasplit-e0299.firebasestorage.app',
    iosBundleId: 'com.example.gasplit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8ER0pknUzZqWWZRsdkhFdYWtwHXKb6n8',
    appId: '1:890593335603:web:626f41995656661b238646',
    messagingSenderId: '890593335603',
    projectId: 'gasplit-e0299',
    authDomain: 'gasplit-e0299.firebaseapp.com',
    storageBucket: 'gasplit-e0299.firebasestorage.app',
    measurementId: 'G-YDR1FRX7DM',
  );
}